### ISSUE TITLE
Form submitted twice on fast click

### ISSUE THREAD

**Issue by scrobbleme** [elliotcondon/acf#689]
Hello,

We are using acf_form for rendering a frontend form. 

The problem is, that we have some users, which click the submit button twice (for whatever reason). This results in double posts.

There should be a way to avoid this:

- [Frontend] Form/ Submit button should be disabled on first click to avoid double clicking
- [Backend] Form should contain some token to avoid multiple submissions

**Comment by elliotcondon** [comment]
Hi @scrobbleme 

Thanks for the bug report and good timing!

I've just fixed this bug in the latest build 5.7.0-RC1. This will be released shortly in the next week of so.
For now, if you need a quick solution, please add some jQuery to simply listen to "form submit" and disable the buttons within the form.

**Comment by pierredebras** [comment]
Hi. Sorry to re-open this older post, but I've tried in both Firefox and Chrome... and you can still press several times the submit button, resulting in submitting the form more than once.

**Comment by elliotcondon** [comment]
HI @pierredebras 

Thanks mate. This issue is still active unfortunately.
We had to revert the change from 5.7.0 after experiencing various "Internet Explorer" related issues.

I'll hopefully take another look at this during the year.

**Comment by Jonpar54** [comment]
Hello, i'm currently using ACF Pro 5.8.7 and I still have the problem. Did you find any solution or patch to prevent multiple submission of a form in front ?

**Comment by golendercaria** [comment]
@elliotcondon any information about the fix ? 

Thank.

**Comment by elliotcondon** [comment]
@Jonpar54 @golendercaria No fix yet, but I hope to solve this during 2020 milestones :)
